### ISSUE TITLE
优化一下更新日志页面罢

### ISSUE THREAD

**Issue by Ad-closeNN** [shiyang0510/pcl2-GK-SY#1]
~~如果快照版修复了这个当我没说~~
东西是写对了 但是`Tooltip`意思不对...
![image](https://github.com/shiyang0510/pcl2-GK-SY/assets/103355026/474a1be7-e751-45e0-a670-8dd1b56c9963)
还是一样 东西写对了 但是`EventType`写错了
**应为`打开网页`**
![image](https://github.com/shiyang0510/pcl2-GK-SY/assets/103355026/14772a50-c205-4067-be92-8d7eace721a8)

**还有上面那个也错了（`开源链接`的`EventTpye`）**

**Comment by shiyang0510** [comment]
你说的是这个的开源代码么？这个是老早的了，我还没有更新

**Comment by shiyang0510** [comment]
因为新版应该是没有这个东西，我记得我改了
